codeforces_crawler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('userinfo.urls')),
]

userinfo/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'userinfo'
urlpatterns = [
    path('',views.index, name='index'),
    path('detail/',views.detail,name='detail'),
    path('compares/',views.Compares,name='Compares'),
    path('teamrating/',views.teamrate,name='teamrate'),
    # path('',views.signup,name='signup'),
    # path('login/',auth_views.LoginView.as_view(template_name='userinfo/login.html'),name='login'),
    # path('logout/',auth_views.LogoutView.as_view(template_name='userinfo/logout.html'),name='logout'),
    #path('redirect/',views.redirect_view,name='redirect_view')
]

userinfo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    sur_name = models.CharField(max_length=100, blank=True)
    
    email = models.CharField(max_length=200,blank=True)

@receiver(post_save,sender=User)

def update_user_profile(sender, instance,created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

# Create your models here.
class ContestDb(models.Model):
    contest_name=models.CharField(max_length=500)
    date=models.DateField()

class Question(models.Model):
    prob_link = models.CharField(max_length=500, default='')
    prob_level = models.CharField(max_length=1,default='')
    prob_rat = models.IntegerField(default=0)
    expression_parsing = models.BooleanField(default=False)
    fft = models.BooleanField(default=False)
    two_pointers = models.BooleanField(default=False)
    binary_search = models.BooleanField(default=False)
    dsu = models.BooleanField(default=False)
    strings = models.BooleanField(default=False)
    number_theory = models.BooleanField(default=False)
    data_structures = models.BooleanField(default=False)
    hashing = models.BooleanField(default=False)
    shortest_paths = models.BooleanField(default=False)
    matrices = models.BooleanField(default=False)
    string_suffix_structures = models.BooleanField(default=False)
    graph_matchings = models.BooleanField(default=False)
    dp = models.BooleanField(default=False)
    dfs_and_similar = models.BooleanField(default=False)
    meet_in_the_middle = models.BooleanField(default=False)
    games = models.BooleanField(default=False)
    schedules = models.BooleanField(default=False)
    constructive_algorithms = models.BooleanField(default=False)
    greedy = models.BooleanField(default=False)
    bitmasks = models.BooleanField(default=False)
    divide_and_conquer = models.BooleanField(default=False)
    flows = models.BooleanField(default=False)
    geometry = models.BooleanField(default=False)
    math = models.BooleanField(default=False)
    sortings = models.BooleanField(default=False)
    ternary_search = models.BooleanField(default=False)
    combinatorics = models.BooleanField(default=False)
    brute_force = models.BooleanField(default=False)
    implementation = models.BooleanField(default=False)
    sat_2 = models.BooleanField(default=False)
    trees = models.BooleanField(default=False)
    probabilities = models.BooleanField(default=False)
    graphs = models.BooleanField(default=False)
    chinese_remainder_theorem = models.BooleanField(default=False)
    interactive = models.BooleanField(default=False)
    other_tag = models.BooleanField(default=False)
    special_problem = models.BooleanField(default=False)

userinfo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    first_name=forms.CharField(max_length=100,help_text='Required.')
    sur_name=forms.CharField(max_length=100,help_text='Required.')
    email=forms.CharField(max_length=200,help_text='Required.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'sur_name', 'email', 'password1', 'password2' )

userinfo/views.py
from django.shortcuts import render,redirect
from .scraping import scrape,only_rating
from .teamrate import team_ratings
from .rank_color import rank_color
from .forms import SignUpForm
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime
import time
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'userinfo/index.html')



def detail(request):
    user = request.POST['user']  # user is the name of the input
    # rank,color,ar,institute,ac,wa,tle,rte,mle,challenged,cpe,skipped,ile,other = scrape(user)
    colorslisttemp = ['rgba(255, 99, 132, 0.2)','rgba(54, 162, 235, 0.2)','rgba(255, 206, 86, 0.2)','rgba(75, 192, 192, 0.2)','rgba(153, 102, 255, 0.2)','rgba(255, 159, 64, 0.2)']
    colorsborderlisttemp = ['rgba(255, 99, 132, 1)','rgba(54, 162, 235, 1)','rgba(255, 206, 86, 1)','rgba(75, 192, 192, 1)','rgba(153, 102, 255, 1)','rgba(255, 159, 64, 1)']
    colorslist = []
    colorsborderlist = []
    for i in range(0,50,1):
        colorslist.append(colorslisttemp[i%6])
        colorsborderlist.append(colorsborderlisttemp[i%6])


    verdict = scrape(user)
    if verdict == False:
        exists = verdict
        messages.error(request, 'Username that you mentioned is incorrect.')
        return HttpResponseRedirect('../')
    elif verdict[1] == False:
        exists = verdict[0]
        contests_given = verdict[1]
        name = verdict[2]
        rating = verdict[3]
        maxrating = verdict[4]
        country = verdict[5]
        city = verdict[6]
        organisation = verdict[7]
        rank = verdict[8]
        maxrank = verdict[9]

        TagList = verdict[10]
        ProbRatList = verdict[11]
        TypeList = verdict[12]
        LangList = verdict[13]
        VerdictList = verdict[14]

        contestTime = verdict[15]
        ranks = verdict[16]
        oldRatings = verdict[17]
        newRatings = verdict[18]
        bestRank = verdict[19]
        worstRank = verdict[20]

        VCList = verdict[21]
        RecentList = verdict[22]
        ProbRecommended = verdict[23]
        TagListAvg = verdict[24]
        FirstTimeChange = verdict[25]
        HeatmapList = verdict[26]
        HeatmapListAC = verdict[27]
        FirstTimeChangeExits=False
        if len(HeatmapList)==0:
            height=0
        else:
            height = (HeatmapList[0][0]-HeatmapList[len(HeatmapList)-1][0]+1)*175
        if('OK' in VerdictList):
            VerdictList['ACCEPTED'] = VerdictList['OK']
            del VerdictList['OK']
        else:
            pass


        TypeList_label = []
        TypeList_data = []

        for i in sorted (TypeList) :
            TypeList_data.append(TypeList[i])
            TypeList_label.append(i)

        LangList_label = []
        LangList_data = []

        for i in sorted (LangList) :
            LangList_data.append(LangList[i])
            LangList_label.append(i)

        ProbRatList_label = []
        ProbRatList_data = []

        for i in sorted (ProbRatList) :
            ProbRatList_data.append(ProbRatList[i])
            ProbRatList_label.append(i)

        VerdictList_label = []
        VerdictList_data = []

        VerdictList = dict(sorted(VerdictList.items(), key=lambda item: item[1],reverse=True))
        for i in VerdictList:
            VerdictList_label.append(i)
            VerdictList_data.append(VerdictList[i])

        TagList_label = []
        TagList_data = []

        TagList = dict(sorted(TagList.items(), key=lambda item: item[1], reverse=True))
        for i in TagList:
            TagList_label.append(i)
            TagList_data.append(TagList[i])

        TagListAvg_label = []
        TagListAvg_data = []

        TagListAvg = dict(sorted(TagListAvg.items(), key=lambda item: item[1], reverse=True))
        for i in TagListAvg:
            TagListAvg_label.append(i)
            TagListAvg_data.append(TagListAvg[i])

        return  render(request, 'userinfo/detail.html',
                       {'user':user,
                       'maxrating':maxrating,
                       'country':country,
                       'city':city,
                       'organisation':organisation,
                       'rank':rank,
                       'maxrank':maxrank,
                       'exists': exists,
                       'contests_given': contests_given,
                       'name': name,
                       'rating': rating,
                       'TagList': TagList,
                       'TagList_data':TagList_data,
                       'TagList_label':TagList_label,
                       'TagListAvg_data':TagListAvg_data,
                       'TagListAvg_label':TagListAvg_label,
                       'VCList':VCList,
                       'RecentList':RecentList,
                       'ProbRecommended':ProbRecommended,
                       'TagListAvg':TagListAvg,
                       'ProbRatList_data':ProbRatList_data,
                       'ProbRatList_label':ProbRatList_label,
                       'TypeList_data':TypeList_data,
                       'TypeList_label':TypeList_label,
                       'VerdictList_data':VerdictList_data,
                       'VerdictList_label':VerdictList_label,
                       'LangList_data':LangList_data,
                       'LangList_label':LangList_label,
                       'colorslist': colorslist,
                       'colorsborderlist':colorsborderlist,
                       'FirstTimeChangeExits':FirstTimeChangeExits,
                       'HeatmapList':HeatmapList,
                       'HeatmapListAC':HeatmapListAC,
                       'height':height
                        }
                       )
    else:
        exists = verdict[0]
        contests_given = verdict[1]
        name = verdict[2]
        rating = verdict[3]
        maxrating = verdict[4]
        country = verdict[5]
        city = verdict[6]
        organisation = verdict[7]
        rank = verdict[8]
        maxrank = verdict[9]

        TagList = verdict[10]
        ProbRatList = verdict[11]
        TypeList = verdict[12]
        LangList = verdict[13]
        VerdictList = verdict[14]

        contestTime = verdict[15]
        ranks = verdict[16]
        oldRatings = verdict[17]
        newRatings = verdict[18]
        bestRank = verdict[19]
        worstRank = verdict[20]

        VCList = verdict[21]
        RecentList = verdict[22]
        ProbRecommended = verdict[23]
        TagListAvg = verdict[24]
        FirstTimeChange = verdict[25]
        HeatmapList = verdict[26]
        HeatmapListAC = verdict[27]
        FirstTimeChangeExits=True

        rank, passrankcolor = rank_color(rating)

        userfirstletter = user[0]
        userremaining = user[1:]

        if ('OK' in VerdictList):
            VerdictList['ACCEPTED'] = VerdictList['OK']
            del VerdictList['OK']
        else:
            pass


        TypeList_label = []
        TypeList_data = []

        for i in sorted (TypeList) :
            TypeList_data.append(TypeList[i])
            TypeList_label.append(i)

        LangList_label = []
        LangList_data = []

        for i in sorted (LangList) :
            LangList_data.append(LangList[i])
            LangList_label.append(i)

        ProbRatList_label = []
        ProbRatList_data = []

        for i in sorted (ProbRatList) :
            ProbRatList_data.append(ProbRatList[i])
            ProbRatList_label.append(i)

        VerdictList_label = []
        VerdictList_data = []

        VerdictList = dict(sorted(VerdictList.items(), key=lambda item: item[1],reverse=True))
        for i in VerdictList:
            VerdictList_label.append(i)
            VerdictList_data.append(VerdictList[i])

        TagList_label = []
        TagList_data = []

        TagList = dict(sorted(TagList.items(), key=lambda item: item[1], reverse=True))
        for i in TagList:
            TagList_label.append(i)
            TagList_data.append(TagList[i])

        TagListAvg_label = []
        TagListAvg_data = []

        TagListAvg = dict(sorted(TagListAvg.items(), key=lambda item: item[1], reverse=True))
        for i in TagListAvg:
            TagListAvg_label.append(i)
            TagListAvg_data.append(TagListAvg[i])

        contestTimegood = []
        for i in (contestTime):
            t = time.strftime('%Y-%m-%d', time.localtime(i))
            #i = datetime.datetime.fromtimestamp(i).strftime('%c')
            contestTimegood.append(t)
        height = (HeatmapList[0][0]-HeatmapList[len(HeatmapList)-1][0]+1)*175
        return render(request, 'userinfo/detail.html',
                      {
                      'user':user,
                      'maxrating':maxrating,
                      'country':country,
                      'city':city,
                      'organisation':organisation,
                      'rank':rank,
                      'maxrank':maxrank,
                      'exists': exists,
                      'contests_given': contests_given,
                      'name': name,
                      'rating': rating,
                      'contestTime':contestTime,
                      'contestTimegood':contestTimegood,
                      'ranks':ranks,
                      'newRatings':newRatings,
                      'bestRank': bestRank,
                      'TagList': TagList,
                      'TagList_data':TagList_data,
                      'TagList_label':TagList_label,
                      'TagListAvg_data':TagListAvg_data,
                      'TagListAvg_label':TagListAvg_label,
                      'VCList':VCList,
                      'RecentList':RecentList,
                      'ProbRecommended':ProbRecommended,
                      'TagListAvg':TagListAvg,

userinfo/templates/userinfo/index.html
{% load static %}

<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Crawler</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/indexStylesheet.css'%}" type="text/css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

  </head>


<body>


  <div class="card-custom">
      <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <a class="navbar-brand" href="{% url 'userinfo:index' %}" style="font-weight: 700; font-family: 'GT Walsheim Pro';">CodeForces Crawler</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <i class="fa fa-angle-double-down"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/AnantShankhdhar/codeforces-crawler" target="_blank" style="font-weight: 700; font-family: 'GT Walsheim Pro';" >Github</a>
            </li>
          </ul>
          <ul class="navbar-nav navbar-right">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-weight: 500; font-family: 'GT Walsheim Pro'; margin-right:3rem;">
                Contributors
              </a>
              <div class="dropdown-menu " aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="https://www.linkedin.com/in/divyam-singal-416720196/" target="_blank" style=" font-family: 'GT Walsheim Pro';">Divyam Singal</a>
                <a class="dropdown-item" href="https://www.linkedin.com/in/manish-prajapati-9970641a0/" target="_blank" style=" font-family: 'GT Walsheim Pro';">Manish Prajapati</a>
                <a class="dropdown-item" href="https://www.linkedin.com/in/anantshankhdhar/" target="_blank" style=" font-family: 'GT Walsheim Pro';">Anant Shankhdhar</a>
              </div>
            </li>

          </ul>
        </div>
      </nav>
    </div>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-3 singleuser card">
      <h3 class="toptext">Check user statistics</h3>
      <form action="{% url 'userinfo:detail' %}" method="post">
          {% csrf_token %}
          <label for="handle">
                  User handle:
          </label><br>
          <input type="text" id="handle" placeholder="handle" required name="user" /><br>
          <input type="submit" value="Submit">

      </form>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-3 comparesuser card">
      <h3 class="toptext">Compare two users</h3>
      <form action="{% url 'userinfo:Compares' %}" method="post">
          {% csrf_token %}
          <label for="Firsthandle" >
                  User handle First:
          </label>
          <br>
          <input type="text" id="Firsthandle"  placeholder = "handle 1" required name="Firstuser"/>
          <br>
          <label for="Secondhandle">
                  User handle Second:
          </label>
          <br>
          <input type="text" id="Secondhandle" placeholder = "handle 2" required name="Seconduser"/>
          <br>
          <input type="submit" value="Submit">
      </form>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-3 teamuser card">
      <h3 class="toptext">Check Team Rating</h3>
      <form action="{% url 'userinfo:teamrate' %}" method="post">
          {% csrf_token %}
          <label for="handle1">
                  User handle1:
          </label><br>
          <input type="text" id="handle1" placeholder="handle 1" name="user1" /><br>
          <label for="handle2">
                  User handle2:
          </label><br>
          <input type="text" id="handle2" name="user2" placeholder="handle 2" /><br>
          <label for="handle3">
                  User handle3:
          </label><br>
          <input type="text" id="handle3" name="user3" placeholder = "handle 3" /><br>
          <label for="handle4">
                  User handle4:
          </label><br>
          <input type="text" id="handle4" name="user4" placeholder = "handle 4" /><br>
          <input type="submit" value="Submit">
          <p>{{error}}</p>
      </form>
    </div>
  </div>
  <br>
  {% if messages %}
    <ul class="messages" style="color: red; ">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
  {% endif %}
  <br>
  <br>
    <div class="row card ">
      <div class="col-md-4">

      </div>
      <div class="col-md-4 thankscard">
        Thanks For Using, visit <a href="https://github.com/AnantShankhdhar/codeforces-crawler" style=" font-family: 'GT Walsheim Pro';" target="_blank">Github</a>
      </div>
      <div class="col-md-4">

      </div>
    </div>
</div>


{% if error_message %}
    <p class="error"><strong>{{ error_message }}</strong></p>
{% endif %}



<script>
    $(document).on('click','.navbar-collapse.in',function(e) {
      if( $(e.target).is('a:not(".dropdown-toggle")') ) {
          $(this).collapse('hide');
      }
    });
  </script>

<!-- Optional Javascript -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>



</body>
</html>

userinfo/templates/userinfo/teamrate.html
{% load static %}
<html>

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Team Rating</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/teamrate.css'%}" type="text/css">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

  </head>
  <body>
    <div class="card-custom">
        <nav class="navbar navbar-expand-lg navbar-light bg-white">
          <a class="navbar-brand" href="{% url 'userinfo:index' %}" style="font-weight: 700; font-family: 'GT Walsheim Pro';">CodeForces Crawler</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-angle-double-down"></i>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                <a class="nav-link" href="https://github.com/AnantShankhdhar/codeforces-crawler" target="_blank" style="font-weight: 700; font-family: 'GT Walsheim Pro';" >Github</a>
              </li>
            </ul>
            <ul class="navbar-nav navbar-right">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-weight: 500; font-family: 'GT Walsheim Pro'; margin-right:3rem;">
                  Contributors
                </a>
                <div class="dropdown-menu " aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="https://www.linkedin.com/in/divyam-singal-416720196/" target="_blank" style=" font-family: 'GT Walsheim Pro';">Divyam Singal</a>
                  <a class="dropdown-item" href="https://www.linkedin.com/in/manish-prajapati-9970641a0/" target="_blank" style=" font-family: 'GT Walsheim Pro';">Manish Prajapati</a>
                  <a class="dropdown-item" href="https://www.linkedin.com/in/anantshankhdhar/" target="_blank" style=" font-family: 'GT Walsheim Pro';">Anant Shankhdhar</a>
                </div>
              </li>

            </ul>
          </div>
        </nav>
      </div>
      <br>
      <div class="container">
        <div class= "Teamrating card text-center">
            <span class="info">
                <p class="ques" style="display:inline">Team Members: </p>
                <p class="ans" style="display:inline">{% for e in exists %}
                    {{ e}}
                {% endfor %} </p>
            </span>
            <span class="info">
                <p class="ques" style="display:inline">Team Rating: </p>
                <p class="ans" style="display:inline">{{ answer }} </p>
            </span>
            <span class="info">
                <p class="ques" style="display:inline">Team Rank: </p>
                <p class="ans" style="display:inline">{{ rank }} </p>
            </span>
            <span class="info">
                <p class="ques" style="display:inline">Team Color: </p>
                <p class="ans" style="display:inline;{% if 'BRed' in color %} color:red; {% else %} color:{{ color}};{% endif %}">{{ color }} </p>
            </span>
            {% if length != 0 %}
                (The following  {{ length }} users don't exists-
                {% for ne in notexists %}
                    {{ ne}}
                {% endfor %}
                .)
            {% endif %}
        </div>
      </div>
      <script>
          $(document).on('click','.navbar-collapse.in',function(e) {
            if( $(e.target).is('a:not(".dropdown-toggle")') ) {
                $(this).collapse('hide');
            }
          });
        </script>

      <!-- Optional Javascript -->
      <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


  </body>


</html>